# imports:
#     - php

# filter:
#     excluded_paths: [vendor/*, test/*]

# build:
#     image: default-bionic

#     nodes:
#         my-tests:
#             environment:
#                 php:
#                     version: 8.3.3
#                 variables:
#                     COMPOSER_ALLOW_SUPERUSER: 1
#                     COMPOSER_MEMORY_LIMIT: -1
#             tests:
#                 override:
#                     - composer install --no-interaction --prefer-dist
#                     - phpunit
#                 coverage:
#                     file: "docs/coverage.clover"
#                     format: "php-clover"

# imports:
#     - php

# filter:
#     excluded_paths: [vendor/*, test/*]

# build:
#     image: default-bionic

#     nodes:
#         my-tests:
#             environment:
#                 php:
#                     version: 8.3.3
#                 variables:
#                     COMPOSER_ALLOW_SUPERUSER: 1
#                     COMPOSER_MEMORY_LIMIT: -1
#         analysis:
#             tests:
#                 override:
#                     - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
#                     - composer install --no-interaction --prefer-dist
#                     - php-scrutinizer-run
#                     #- phpcs-run # Not used, missing config file
#     tests:
#         override:
#             -   command: "composer phpunit"
#                 # command: "XDEBUG_MODE=coverage vendor/bin/phpunit"
#                 coverage:
#                     file: "docs/coverage.clover"
#                     format: "php-clover"

imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:
    image: default-bionic

    nodes:
        my-tests:
            environment:
                php:
                    version: 8.3.3
                variables:
                    COMPOSER_ALLOW_SUPERUSER: 1
                    COMPOSER_MEMORY_LIMIT: -1
            tests:
                override:
                    - command: "composer clear-cache"
                    - command: "composer install --no-interaction --prefer-dist -vvv"
                    - command: "php bin/console doctrine:database:create --env=test"
                    - command: "php bin/console doctrine:migrations:migrate --env=test --no-interaction"
                    - command: "php bin/console doctrine:fixtures:load --env=test --no-interaction"
                    - command: "yarn install --frozen-lockfile"
                    - command: "yarn encore production"
                    - command: "rm -rf docs/coverage.clover"
                    - command: "XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover=docs/coverage.clover"
                    - command: "composer phpunit --coverage-clover=docs/coverage.clover"
