imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:
    image: default-bionic

    nodes:
        my-tests:
            environment:
                php:
                    version: 8.3.3
                variables:
                    COMPOSER_ALLOW_SUPERUSER: 1
                    COMPOSER_MEMORY_LIMIT: -1
            tools:
                composer: 2
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
    tests:
        override:
            -   command: "composer install --no-interaction --prefer-dist"
            -   command: "composer phpunit"
                coverage:
                    file: "docs/coverage.clover"
                    format: "php-clover"