<?php

namespace ContainerOpJ0OW5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5fUDvKFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5fUDvKF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5fUDvKF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'renderer' => ['privates', 'App\\Service\\MarkdownPageRenderer', 'getMarkdownPageRendererService', true],
            'fishStockRepository' => ['privates', 'App\\Repository\\FishStockRepository', 'getFishStockRepositoryService', true],
            'marineProtectionRepository' => ['privates', 'App\\Repository\\MarineProtectionRepository', 'getMarineProtectionRepositoryService', true],
        ], [
            'renderer' => 'App\\Service\\MarkdownPageRenderer',
            'fishStockRepository' => 'App\\Repository\\FishStockRepository',
            'marineProtectionRepository' => 'App\\Repository\\MarineProtectionRepository',
        ]);
    }
}
