<?php

namespace ContainerN9jWx8p;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XgiDUJ8Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.XgiDUJ8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XgiDUJ8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'markdownParser' => ['services', 'App\\Service\\MarkdownParser', 'getMarkdownParserService', true],
        ], [
            'markdownParser' => 'App\\Service\\MarkdownParser',
        ]);
    }
}
