<?php

namespace ContainerN9jWx8p;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGameControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\GameController' shared autowired service.
     *
     * @return \App\Controller\GameController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/GameController.php';
        include_once \dirname(__DIR__, 4).'/src/Game/GameService.php';

        $container->services['App\\Controller\\GameController'] = $instance = new \App\Controller\GameController(($container->privates['App\\Game\\GameService'] ??= new \App\Game\GameService()));

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\GameController', $container));

        return $instance;
    }
}
