<?php

namespace ContainerN9jWx8p;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMarkdownPageRendererService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\MarkdownPageRenderer' shared autowired service.
     *
     * @return \App\Service\MarkdownPageRenderer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/MarkdownPageRenderer.php';
        include_once \dirname(__DIR__, 4).'/src/Service/MarkdownParser.php';

        return $container->privates['App\\Service\\MarkdownPageRenderer'] = new \App\Service\MarkdownPageRenderer(($container->services['App\\Service\\MarkdownParser'] ??= new \App\Service\MarkdownParser()));
    }
}
