<?php

namespace ContainerTPQlFl3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CZkmifkService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.cZkmifk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cZkmifk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'renderer' => ['privates', 'App\\Service\\MarkdownPageRenderer', 'getMarkdownPageRendererService', true],
        ], [
            'renderer' => 'App\\Service\\MarkdownPageRenderer',
        ]);
    }
}
