<?php

namespace ContainerTPQlFl3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getControllerTwigService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\ControllerTwig' shared autowired service.
     *
     * @return \App\Controller\ControllerTwig
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ControllerTwig.php';

        $container->services['App\\Controller\\ControllerTwig'] = $instance = new \App\Controller\ControllerTwig();

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\ControllerTwig', $container));

        return $instance;
    }
}
