<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                'build/runtime.620a04ca.js',
                'build/app.5c5da79f.js',
            ],
            'css' => [
                'build/app.3b554f14.css',
            ],
        ],
        'proj' => [
            'js' => [
                'build/runtime.620a04ca.js',
                'build/293.bab352a1.js',
                'build/proj.f8c4f82e.js',
            ],
            'css' => [
                'build/proj.95b8b530.css',
            ],
        ],
    ],
],

]];
