<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJLn3yCE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJLn3yCE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJLn3yCE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJLn3yCE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJLn3yCE\App_KernelDevDebugContainer([
    'container.build_hash' => 'JLn3yCE',
    'container.build_id' => '27c6464c',
    'container.build_time' => 1724502494,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJLn3yCE');
